# This was generated by AI just to test this

import numpy as np
import plotly.graph_objects as go

# 1. Define the grid and test function: f(x, y) = sin(x) * cos(y)
x = np.linspace(-3, 3, 100)
y = np.linspace(-3, 3, 100)
X, Y = np.meshgrid(x, y)
Z = np.sin(X) * np.cos(Y)

# 2. Create the 3D surface trace with transparency
surface = go.Surface(
    z=Z,
    x=X,
    y=Y,
    colorscale="Viridis",
    opacity=0.75,
    name="f(x, y)",
)

# 3. Analytical partial derivatives for the vector field
U = np.cos(X) * np.cos(Y)
V = -np.sin(X) * np.sin(Y)
W = np.zeros_like(U)  # 2D gradient projected onto 3D space

# Subsample grid for the vector field so it isn't overcrowded
step = 10
xs = X[::step, ::step].flatten()
ys = Y[::step, ::step].flatten()
zs = -1.5 * np.ones_like(xs)  # Positioned flat on the floor
us = U[::step, ::step].flatten()
vs = V[::step, ::step].flatten()
ws = W[::step, ::step].flatten()

# 4. Create the 3D vector field trace (Quiver equivalent)
cones = go.Cone(
    x=xs,
    y=ys,
    z=zs,
    u=us,
    v=vs,
    w=ws,
    sizemode="absolute",
    sizeref=0.15,
    colorscale="Reds",
    showscale=False,
    name="Gradient Field",
)

# 5. Combine traces into the figure
fig = go.Figure(data=[surface, cones])

# 6. Enable projected floor contours and layout styling
fig.update_traces(
    contours_z={
        "show": True,
        "usecolormap": True,
        "project_z": True,
        "highlightcolor": "limegreen",
    },
    selector={"type": "surface"},
)

fig.update_layout(
    title="Smooth WebGL Multivariable Calculus & Gradient Field",
    scene={
        "xaxis_title": "X Axis",
        "yaxis_title": "Y Axis",
        "zaxis_title": "Z Axis",
        "aspectratio": {"x": 1, "y": 1, "z": 0.7},
    },
    width=900,
    height=700,
)

# Opens an interactive, hardware-accelerated 60fps window in your browser
fig.show()

# Optional: Export straight to a high-res PDF or image for your assignment
fig.write_image("calculus_homework_plot.png")
